import{a as u,S as f,i}from"./assets/vendor-D0cagnvz.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const p="49011950-2d803ac0681f77f6ebc5cb6af",g="https://pixabay.com/api/";async function y(n){try{return(await u.get(g,{params:{key:p,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:20}})).data.hits}catch(r){throw console.error("Error fetching images:",r),r}}function h(n){const r=document.getElementById("gallery"),o=n.map(({webformatURL:a,largeImageURL:e,tags:t,likes:s,views:l,comments:d,downloads:m})=>`
        <a href="${e}" class="gallery-item">
            <img src="${a}" alt="${t}" loading="lazy">
            <div class="info">
                <p><b>Likes:</b> ${s}</p>
                <p><b>Views:</b> ${l}</p>
                <p><b>Comments:</b> ${d}</p>
                <p><b>Downloads:</b> ${m}</p>
            </div>
        </a>`).join("");r.innerHTML=o}const b=document.getElementById("search-form"),L=document.getElementById("search-input"),E=document.getElementById("gallery"),c=document.getElementById("loader"),w=new f(".gallery a",{captionsData:"alt",captionDelay:250});b.addEventListener("submit",async n=>{n.preventDefault();const r=L.value.trim();if(!r){i.warning({title:"Warning",message:"Please enter a search term!"});return}E.innerHTML="",c.classList.remove("hidden");try{const o=await y(r);if(o.length===0){i.error({title:"Error",message:"No images found for this query."});return}h(o),w.refresh()}catch{i.error({title:"Error",message:"Something went wrong. Try again later."})}finally{c.classList.add("hidden")}});
//# sourceMappingURL=index.js.map
